# Generated by Django 2.0 on 2018-01-01 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated')),
            ],
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beres.Topic'),
        ),
        migrations.AddField(
            model_name='resource',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beres.Topic'),
        ),
    ]
