# Generated by Django 2.0 on 2018-01-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
