# Generated by Django 2.0 on 2018-01-05 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beres', '0002_resource_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='free',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
