# Generated by Django 2.0 on 2018-01-12 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beres', '0003_resource_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='votes',
        ),
        migrations.AddField(
            model_name='resource',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubTopic',
        ),
        migrations.AddField(
            model_name='votes',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beres.Resource'),
        ),
        migrations.AddField(
            model_name='votes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
