# Generated by Django 2.0 on 2018-01-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beres', '0005_votes_vote_up'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='vote_up',
            new_name='voted_up',
        ),
    ]
