# Generated by Django 2.0 on 2018-01-25 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beres', '0007_auto_20180124_0101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='name',
        ),
    ]
